"""empty message

Revision ID: 249de7c46bb3
Revises: 5c911049e08a
Create Date: 2023-03-29 14:43:26.852688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249de7c46bb3'
down_revision = '5c911049e08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pupils',
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('pupil_name', sa.String(length=30), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('eng_group', sa.Integer(), nullable=True),
    sa.Column('second_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eng_group'], ['english_groups.group_id'], ),
    sa.ForeignKeyConstraint(['grade'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['second_group'], ['second_lang_groups.group_id'], ),
    sa.PrimaryKeyConstraint('pupil_id')
    )
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pupils_pupil_name'), ['pupil_name'], unique=True)

    with op.batch_alter_table('english_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_english_groups_group_name')
        batch_op.create_index(batch_op.f('ix_english_groups_group_name'), ['group_name'], unique=False)

    with op.batch_alter_table('second_lang_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_second_lang_groups_group_name')
        batch_op.create_index(batch_op.f('ix_second_lang_groups_group_name'), ['group_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('second_lang_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_second_lang_groups_group_name'))
        batch_op.create_index('ix_second_lang_groups_group_name', ['group_name'], unique=False)

    with op.batch_alter_table('english_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_english_groups_group_name'))
        batch_op.create_index('ix_english_groups_group_name', ['group_name'], unique=False)

    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pupils_pupil_name'))

    op.drop_table('pupils')
    # ### end Alembic commands ###
