"""empty message

Revision ID: 5c911049e08a
Revises: 
Create Date: 2023-03-17 14:32:24.542498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c911049e08a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('english_teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    with op.batch_alter_table('english_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_english_teachers_teacher_name'), ['teacher_name'], unique=True)

    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('grade_id')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_grade_name'), ['grade_name'], unique=True)

    op.create_table('second_lang_teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    with op.batch_alter_table('second_lang_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_second_lang_teachers_teacher_name'), ['teacher_name'], unique=True)

    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=30), nullable=True),
    sa.Column('subject_name_eng', sa.String(length=30), nullable=True),
    sa.Column('subj_min', sa.Integer(), nullable=True),
    sa.Column('subj_max', sa.Integer(), nullable=True),
    sa.Column('subj_value', sa.Integer(), nullable=True),
    sa.Column('subj_general', sa.Boolean(), nullable=True),
    sa.Column('subj_10', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_subject_name'), ['subject_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_subject_name_eng'), ['subject_name_eng'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('passwd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('curriculum',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('les_subject', sa.Integer(), nullable=True),
    sa.Column('les_grade', sa.Integer(), nullable=True),
    sa.Column('les_number', sa.Integer(), nullable=True),
    sa.Column('les_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['les_grade'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['les_subject'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('english_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_grade', sa.Integer(), nullable=True),
    sa.Column('group_teacher', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('group_level', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['group_grade'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['group_teacher'], ['english_teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    with op.batch_alter_table('english_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_english_groups_group_level'), ['group_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_english_groups_group_name'), ['group_name'], unique=True)

    op.create_table('second_lang_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_lang', sa.Integer(), nullable=True),
    sa.Column('group_grade', sa.Integer(), nullable=True),
    sa.Column('group_teacher', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('group_level', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['group_grade'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['group_teacher'], ['second_lang_teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    with op.batch_alter_table('second_lang_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_second_lang_groups_group_level'), ['group_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_second_lang_groups_group_name'), ['group_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('second_lang_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_second_lang_groups_group_name'))
        batch_op.drop_index(batch_op.f('ix_second_lang_groups_group_level'))

    op.drop_table('second_lang_groups')
    with op.batch_alter_table('english_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_english_groups_group_name'))
        batch_op.drop_index(batch_op.f('ix_english_groups_group_level'))

    op.drop_table('english_groups')
    op.drop_table('curriculum')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_subject_name_eng'))
        batch_op.drop_index(batch_op.f('ix_subjects_subject_name'))

    op.drop_table('subjects')
    with op.batch_alter_table('second_lang_teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_second_lang_teachers_teacher_name'))

    op.drop_table('second_lang_teachers')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_grade_name'))

    op.drop_table('grades')
    with op.batch_alter_table('english_teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_english_teachers_teacher_name'))

    op.drop_table('english_teachers')
    # ### end Alembic commands ###
